#!/bin/zsh

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export ZDOTDIR=${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

# Set the list of directories that zsh searches for commands.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /home/linuxbrew/.linuxbrew(N)
  /usr/local/{,s}bin(N)
  $HOME/.cargo/{,s}bin(N)
  $HOME/.local/share/mise/shims(N)
  $path
)

export MANPAGER='nvim +Man!'
export EDITOR="nvim"
export CHTSH_QUERY_OPTIONS="style=lovelace"
