[tools]
bat = "latest"
chezmoi = "latest"
delta = "latest"
dua = "latest"
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
glow = "latest"
go = "latest"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
mprocs = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
