# change prefix to backtick
set -g prefix `
unbind c-b
bind ` send-prefix

# windows
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
unbind [ # for copy-mode
bind [ swap-window -d -t -1
bind ] swap-window -d -t +1
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# constants (from tmux-sensible as well)
set -g default-terminal "xterm-ghostty"
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g mode-keys vi
set -g set-clipboard on
set -g mouse on
set -s focus-events on
set -s extended-keys on
setw -g aggressive-resize on

# keybinds
bind m set -g mouse
unbind h
unbind j
unbind k
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# copy mode
bind Enter copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel

# tpm
set -g @plugin 'tmux-plugins/tpm' # I
# theming
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
set -g @tmux-gruvbox-statusbar-alpha 'true'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @cpu_percentage_format "%3d%"
set -g @ram_percentage_format "%3d%"
set -g @tmux-gruvbox-right-status-x '#{cpu_percentage}  |#{ram_percentage}  '
# other plugins
set -g @plugin 'tmux-plugins/tmux-resurrect' # Ctrl+s, Ctrl+r
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '0' # only enable for certain environments
set -g @plugin 'jaclu/tmux-menus' # \\
set -g @plugin 'sainnhe/tmux-fzf' # o
TMUX_FZF_LAUNCH_KEY="o"
set -g @plugin 'Morantron/tmux-fingers' # y
set -g @fingers-key y
set -g @plugin 'tmux-plugins/tmux-logging' # Alt/Shift P
set -g @plugin 'laktak/extrakto' # Space
set -g @extrakto_clip_tool_run "tmux_osc52"
set -g @extrakto_key Space
set -g @plugin 'roosta/tmux-fuzzback' # /
unbind /
set -g @fuzzback-bind /

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
# remember to clone the repo before using it
# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
run '~/.config/tmux/plugins/tpm/tpm'
